version: '3.5'
services:
    backend:
        build: 
            context: .
            dockerfile: Backend-Dockerfile
        networks:
            net:
                aliases: 
                    - factuapi
    frontend:
        build:
            context: .
            dockerfile: Frontend-Dockerfile
        depends_on:
            - backend
        volumes:
            - ./frontend:/app/factuweb_frontend:rw
        ports:
            - "5000:5000"
        networks:
            net:
                aliases: 
                    - factuweb
        links:
            - backend
networks:
    net:
        name: factuweb_net
        driver: bridge
